syntax= "proto3";
package account;
message Account{
    string id=1;
    string code=2;
    float balance=3;
    string user_id=4;
}

message GetAccountRequest {
  string account_id=1;
}
message GetAccountResponse {
    Account searchedAccount=1;
}
message AddAccountRequest {
    Account account=1;
}
message AddAccountResponse {
    Account account=1;
}
message DeleteAccountRequest {
  string account_id=1;
}
message DeleteAccountResponse {
    bool success=1;
    string message=2;
}
message UpdateAccountRequest {
  string account_id=1;
  Account account=2;
}
message UpdateAccountResponse {
    Account account=1;
}

message SearchAccountsRequest {
  float account_balance=1;
}
message SearchAccountsResponse {
    repeated Account matchingAccounts=1;
}

message WithdrawMoneyRequest{
    string user_id=1;
    string account_id=2;
    float amount=3;
}
message WithdrawMoneyResponse{
    Account account=1;
    string message=2;
}
message DepositMoneyRequest{
    string user_id=1;
    string account_id=2;
    float amount=3;
}
message DepositMoneyResponse{
    Account account=1; 
    string message=2;
}



service AccountService {
    rpc GetAccount(GetAccountRequest) returns (GetAccountResponse);
    rpc AddAccount(AddAccountRequest) returns (AddAccountResponse);
    rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);
    rpc UpdateAccount(UpdateAccountRequest) returns (UpdateAccountResponse);
    rpc SearchAccounts(SearchAccountsRequest) returns (SearchAccountsResponse);
    rpc WithdrawMoney(WithdrawMoneyRequest) returns (WithdrawMoneyResponse);
    rpc DepositMoney(DepositMoneyRequest) returns (DepositMoneyResponse);
}
