type User{
    id:String!
    name: String!
    CIN: String!
    account_id: String!
    account: Account
}

type Account{
    id: String!
    code: String!
    balance: Float!
    user_id: String!
    user: User
}

type Query{
    getUser(id: String!): User
    getUsers:[User]
    getAccount(id: String!): Account
    getAccounts:[Account]
}

type Mutation {
    addUser(id:String!, name:String!, CIN:String!,account_id:String!): User
    updateUser(user_id:String!, id:String!, name:String!, CIN:String!,account_id:String!): User
    addAccount(id:String,code:String!,balance:Float!,user_id:String!): Account
    updateAccount(accountId:String!,id:String,code:String!,balance:Float!,user_id:String!): User

}