type User{
    id:String!
    name: String!
    CIN: String!
    account_id: String!
    account: Account
}

type Account{
    id: String!
    code: String!
    balance: Float!
    user_id: String!
    user: User
}
type DepositMoneyResponsePayload {
    message: String!
    account: Account
}

type Query{
    getUser(id: String!): User
    getUsers:[User]
    getAccount(id: String!): Account
    getAccounts(balance: Float):[Account]
}

type Mutation {
    addUser(id:String!, name:String!, CIN:String!,account_id:String!): User
    updateUser(user_id:String!, id:String!, name:String!, CIN:String!,account_id:String!): User
    deleteUser(userId:String!): String
    addAccount(id:String,code:String!,balance:Float!,user_id:String!): Account
    updateAccount(accountId:String!,id:String,code:String!,balance:Float!,user_id:String!): Account
    deleteAccount(accountId:String!):String
    withrawMoney(userId: String!, accountId: String!, amount: Float!): DepositMoneyResponsePayload
    depositMoney(userId: String!, accountId: String!, amount: Float!): DepositMoneyResponsePayload

}

