scalar Date
type User{
    id:String!
    name: String!
    CIN: String!
    account_id: String!
    account: Account
}

type Account{
    id: String!
    code: String!
    balance: Float!
    user_id: String!
    user: User
}
type DepositMoneyResponsePayload {
    message: String!
    account: Account
}
enum Status {
    PENDING
    SUCCESS
    FAILED
    REVERTED
}

type Transaction {
    id: String!
    senderAccountId: String!
    receiverAccountId: String!
    amount: Float!
    status: Status!
    timeStamp: Date!
}

type TransferMoneyResponsePayload {
    message: String!
    transaction: Transaction
}

type RevertTransactionResponsePayload {
    message: String!
    transaction: Transaction
}

type Query{
    getUser(id: String!): User
    getUsers:[User]
    getAccount(id: String!): Account
    getAccounts(balance: Float):[Account]
    getTransaction(id: String!): Transaction
    getTransactions: [Transaction]
}

type Mutation {
    addUser(id:String!, name:String!, CIN:String!,account_id:String!): User
    updateUser(user_id:String!, id:String!, name:String!, CIN:String!,account_id:String!): User
    deleteUser(userId:String!): String
    addAccount(id:String,code:String!,balance:Float!,user_id:String!): Account
    updateAccount(accountId:String!,id:String,code:String!,balance:Float!,user_id:String!): Account
    deleteAccount(accountId:String!):String
    withrawMoney(userId: String!, accountId: String!, amount: Float!): DepositMoneyResponsePayload
    depositMoney(userId: String!, accountId: String!, amount: Float!): DepositMoneyResponsePayload
    transferMoney(senderAccountId: String!, receiverAccountId: String!, amount: Float!): TransferMoneyResponsePayload
    revertTransaction(transaction_id: String!): RevertTransactionResponsePayload
}

