syntax = "proto3";
package transaction;

message Transaction{
    string id=1;
    string senderAccountId=2;
    string receiverAccountId=3;
    float amount=4;
    string timeStamp=5;
    Status status=6;
}
enum Status{
    PENDING=0;
    SUCCESS=1;
    FAILED=2;
    REVERTED=3;
}

message TransferMoneyRequest{
    //Transaction transaction=1;
    string senderAccountId=1;
    string receiverAccountId=2;
    float amount=3;
}
message TransferMoneyResponse{
    string message=1;
    Transaction transaction=2;
}
message RevertTransactionRequest{
    string transaction_id=1;
}
message RevertTransactionResponse{
    string message=1;
    Transaction transaction=2;
}

message GetTransactionsRequest{

}
message GetTransactionsResponse{
    repeated Transaction transactions = 1;
}

service TransactionService {
  rpc TransferMoney(TransferMoneyRequest) returns (TransferMoneyResponse);
  rpc RevertTransaction(RevertTransactionRequest) returns (RevertTransactionResponse);
  rpc GetAllTransactions(GetTransactionsRequest) returns (GetTransactionsResponse);
}